import type { Metadata } from "next";
import "./globals.css";
import { hues } from "./tools";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        style={{backgroundColor: hues.bg, color: hues["text-secondary"]}}
      >
        {children}
      </body>
    </html>
  );
}
